language: rust
rust:
    - nightly
sudo: false
before_script:
    - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
script:
    - travis-cargo build
    - travis-cargo test
    - travis-cargo doc
after_success:
    - git config user.name "Travis-CI Doc Bot"
    - git config user.email "willusher.life@gmail.com"
      # upload the documentation from the build with beta (automatically only actually
      # runs on the master branch)
      #- travis-cargo --only nightly doc-upload

