[package]
name = "tray_rust"
version = "0.0.1"
authors = ["Will Usher <will@willusher.io>"]

[[bin]]
name = "tray_rust"
doc = false

[dependencies]
enum-set = "0.0.6"
rand = "0.3.14"
rustc-serialize = "0.3.18"
docopt = "0.6.78"
image = "0.7.0"
num_cpus = "0.2.11"
tobj = "0.1.1"
byteorder = "0.4.2"
serde_json = "0.7.0"
scoped_threadpool = "0.1.7"
bspline = "0.2.2"
clock_ticks = "0.1.0"
bincode = "0.5.0"
mio = "0.5.0"
la = "0.2.0"
clippy = { version = "0.0.55", optional = true }

[profile.release]
# How to send extra compiler flag for -march=native equivalent in Rust
# flag is `-C target-cpu=native`
opt-level = 3
debug = false
rpath = false
lto = true

[features]
unstable = ["clippy"]

