[package]

name = "tray_rust"
version = "0.0.1"
authors = ["Will Usher <willusher.life@gmail.com>"]

[[bin]]

name = "tray_rust"
doc = false

[dependencies]

rand = "0.1.2"
collect = "0.0.23"
rustc-serialize = "0.3.0"
docopt = "0.6.39"

[dependencies.image]

git = "https://github.com/PistonDevelopers/image"

[profile.release]

# How to send extra compiler flag for -march=native equivalent in Rust
# flag is `-C target-cpu=native`
opt-level = 3
debug = false
rpath = false
lto = true

