[package]

name = "tray_rust"
version = "0.0.1"
authors = ["Will Usher <willusher.life@gmail.com>"]

[[bin]]

name = "tray_rust"
doc = false

[dependencies]

rand = "0.2.0"
enum-set = "0.0.1"
threadpool = "0.1.1"
rustc-serialize = "0.3.0"
docopt = "0.6.52"
image = "0.2.1"

[profile.release]

# How to send extra compiler flag for -march=native equivalent in Rust
# flag is `-C target-cpu=native`
opt-level = 3
debug = false
rpath = false
lto = true

