[package]

name = "tray_rust"
version = "0.0.1"
authors = ["Will Usher <willusher.life@gmail.com>"]

[[bin]]

name = "tray_rust"
doc = false

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true

