[package]
name = "tray_rust"
version = "0.0.1"
authors = ["Will Usher <willusher.life@gmail.com>"]

[[bin]]
name = "tray_rust"
doc = false

[dependencies]
enum-set = "0.0.5"
rand = "0.3.8"
rustc-serialize = "0.3.15"
docopt = "0.6.70"
image = "0.3.11"
num_cpus = "0.2.6"
tobj = "0.0.9"
byteorder = "0.3.11"
serde_json = "0.5.0"
scoped_threadpool = "0.1.6"

[profile.release]
# How to send extra compiler flag for -march=native equivalent in Rust
# flag is `-C target-cpu=native`
opt-level = 3
debug = false
rpath = false
lto = true

[features]
unstable = []

